#ifndef OPENTEC_BASE_SYSTEM_NOTICE_H
#define OPENTEC_BASE_SYSTEM_NOTICE_H

#include <stdint.h>

typedef enum {
    SYSTEM_NOTICE_NONE,
    SYSTEM_NOTICE_TUNING_MENU_RESET,
    SYSTEM_NOTICE_WHEEL_CENTER_CALIBRATED,
    SYSTEM_NOTICE_POSITION_SENSOR_TEST_SUCCEEDED,
    SYSTEM_NOTICE_POSITION_SENSOR_TEST_STARTED,
    SYSTEM_NOTICE_POSITION_SENSOR_TEST_FAILED,
    SYSTEM_NOTICE_TORQUE_REDUCED,
    SYSTEM_NOTICE_MOTOR_CALIBRATION_DISCONNECT_WHEEL,
    SYSTEM_NOTICE_MOTOR_CALIBRATION_UNSUPPORTED,
    SYSTEM_NOTICE_MOTOR_CALIBRATION_ONGOING,
    SYSTEM_NOTICE_MOTOR_CALIBRATION_COMPLETED,
    SYSTEM_NOTICE_MOTOR_CALIBRATION_ERASED,
    SYSTEM_NOTICE_STANDARD_TUNING_MODE,
    SYSTEM_NOTICE_ADVANCED_TUNING_MODE,
    SYSTEM_NOTICE_MAXIMUM_ROTATIONS_EXCEEDED,
    SYSTEM_NOTICE_SHUTDOWN,
    SYSTEM_NOTICE_UNSUPPORTED_WHEEL_INVERTED,
    SYSTEM_NOTICE_UNSUPPORTED_WHEEL_OUTLINED,
    SYSTEM_NOTICE_ALTERNATIVE_SHIFTER_ENABLED,
    SYSTEM_NOTICE_ALTERNATIVE_SHIFTER_DISABLED,
} SystemNoticeKind;

typedef struct {
    SystemNoticeKind kind;
    uint32_t deadline_ms;
} SystemNotice;

void system_notice_init(SystemNotice *notice);
void system_notice_show(SystemNotice *notice, SystemNoticeKind kind, uint32_t now_ms);
void system_notice_update(SystemNotice *notice, uint32_t now_ms);

#endif
