#ifndef FREEMASTER_CFG_H
#define FREEMASTER_CFG_H

#define FMSTR_PLATFORM_CORTEX_M 1
#define FMSTR_TRANSPORT FMSTR_PDBDM
#define FMSTR_COMM_BUFFER_SIZE 240U
#define FMSTR_USE_READMEM 1
#define FMSTR_USE_WRITEMEM 1
#define FMSTR_USE_WRITEMEMMASK 1

#endif
