#ifndef OPENTEC_BASE_FORCE_FEEDBACK_SCRIPT_MATH_H
#define OPENTEC_BASE_FORCE_FEEDBACK_SCRIPT_MATH_H

#include <stdbool.h>
#include <stdint.h>

typedef uint8_t ForceFeedbackScriptMathOperation;

enum {
    FORCE_FEEDBACK_SCRIPT_MATH_ADD = 0x10,
    FORCE_FEEDBACK_SCRIPT_MATH_SUBTRACT = 0x11,
    FORCE_FEEDBACK_SCRIPT_MATH_MULTIPLY = 0x12,
    FORCE_FEEDBACK_SCRIPT_MATH_DIVIDE = 0x13,
    FORCE_FEEDBACK_SCRIPT_MATH_MODULO = 0x14,
    FORCE_FEEDBACK_SCRIPT_MATH_SQUARE = 0x15,
    FORCE_FEEDBACK_SCRIPT_MATH_CUBE = 0x16,
    FORCE_FEEDBACK_SCRIPT_MATH_SQUARE_ROOT = 0x17,
    FORCE_FEEDBACK_SCRIPT_MATH_SIGN = 0x18,
    FORCE_FEEDBACK_SCRIPT_MATH_ABSOLUTE = 0x19,
    FORCE_FEEDBACK_SCRIPT_MATH_RECIPROCAL = 0x1a,
    FORCE_FEEDBACK_SCRIPT_MATH_SINE = 0x20,
    FORCE_FEEDBACK_SCRIPT_MATH_COSINE = 0x21,
    FORCE_FEEDBACK_SCRIPT_MATH_TANGENT = 0x22,
    FORCE_FEEDBACK_SCRIPT_MATH_MULTIPLY_PI = 0x2a,
    FORCE_FEEDBACK_SCRIPT_MATH_DIVIDE_PI = 0x2b,
    FORCE_FEEDBACK_SCRIPT_MATH_DEGREES_TO_RADIANS = 0x2c,
    FORCE_FEEDBACK_SCRIPT_MATH_RADIANS_TO_DEGREES = 0x2d,
};

typedef struct {
    float value;
    bool writes_value;
} ForceFeedbackScriptMathResult;

ForceFeedbackScriptMathResult
force_feedback_script_math_evaluate(ForceFeedbackScriptMathOperation operation, float first,
                                    float second);

#endif
