#ifndef FREEMASTER_CFG_H
#define FREEMASTER_CFG_H

#define FMSTR_PLATFORM_CORTEX_M 1
#define FMSTR_LONG_INTR 1
#define FMSTR_SHORT_INTR 0
#define FMSTR_POLL_DRIVEN 0
#define FMSTR_TRANSPORT FMSTR_SERIAL
#define FMSTR_SERIAL_DRV FMSTR_SERIAL_MCUX_UART
#define FMSTR_SERIAL_BASE UART0
#define FMSTR_COMM_BUFFER_SIZE 60U
#define FMSTR_USE_READMEM 1
#define FMSTR_USE_WRITEMEM 1
#define FMSTR_USE_WRITEMEMMASK 1

#endif
